In [2]:
import numpy as np


In [138]:
np.random.seed(55)
a=np.random.randint(20,80,(8,9))
a

array([[33, 46, 59, 28, 49, 57, 75, 57, 47],
       [53, 74, 68, 55, 66, 50, 33, 50, 32],
       [44, 67, 27, 51, 53, 73, 75, 28, 71],
       [30, 49, 59, 49, 47, 20, 75, 63, 65],
       [47, 38, 69, 44, 68, 34, 76, 30, 79],
       [79, 48, 61, 64, 44, 72, 49, 64, 41],
       [33, 72, 61, 78, 53, 65, 44, 38, 36],
       [65, 75, 47, 38, 76, 62, 52, 73, 30]])

In [114]:
a[-1]

array([65, 75, 47, 38, 76, 62, 52, 73, 30])

In [116]:
a.ndim

2

In [118]:
a.shape

(8, 9)

In [122]:
a

array([[33, 46, 59, 28, 49, 57, 75, 57, 47],
       [53, 74, 68, 55, 66, 50, 33, 50, 32],
       [44, 67, 27, 51, 53, 73, 75, 28, 71],
       [30, 49, 59, 49, 47, 20, 75, 63, 65],
       [47, 38, 69, 44, 68, 34, 76, 30, 79],
       [79, 48, 61, 64, 44, 72, 49, 64, 41],
       [33, 72, 61, 78, 53, 65, 44, 38, 36],
       [65, 75, 47, 38, 76, 62, 52, 73, 30]])

In [124]:
a[3]

array([30, 49, 59, 49, 47, 20, 75, 63, 65])

In [126]:
a[7,8]

30

In [128]:
a[row_start: row_end : row_step , col_start: col_end:col_step]

NameError: name 'row_start' is not defined

In [130]:
a[2:6]

array([[44, 67, 27, 51, 53, 73, 75, 28, 71],
       [30, 49, 59, 49, 47, 20, 75, 63, 65],
       [47, 38, 69, 44, 68, 34, 76, 30, 79],
       [79, 48, 61, 64, 44, 72, 49, 64, 41]])

In [132]:
a[2:6:1,1:7:2]

array([[67, 51, 73],
       [49, 49, 20],
       [38, 44, 34],
       [48, 64, 72]])

In [140]:
a[1:5,1:6]

array([[74, 68, 55, 66, 50],
       [67, 27, 51, 53, 73],
       [49, 59, 49, 47, 20],
       [38, 69, 44, 68, 34]])

In [143]:
import pandas as pd

In [161]:
k=[[4,7],[2,9],[7,3],[90,50]]
k

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [165]:
t=np.array(k)
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [175]:
t.ndim

2

In [179]:
pd.Series(t)

ValueError: Data must be 1-dimensional, got ndarray of shape (4, 2) instead

In [181]:
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [171]:
pd.Series(k)

0      [4, 7]
1      [2, 9]
2      [7, 3]
3    [90, 50]
dtype: object

In [177]:
pd.DataFrame(t)

0   1
0   4   7
1   2   9
2   7   3
3  90  50

In [187]:
df=pd.DataFrame(t,columns=['name','sub'],index=[289,290,291,292])
df

name  sub
289     4    7
290     2    9
291     7    3
292    90   50

In [189]:
df.columns

Index(['name', 'sub'], dtype='object')

In [195]:
df['sub']

289     7
290     9
291     3
292    50
Name: sub, dtype: int32

In [197]:
df.sub

<bound method DataFrame.sub of      name  sub
289     4    7
290     2    9
291     7    3
292    90   50>

In [199]:
df['sub'].mean

<bound method Series.mean of 289     7
290     9
291     3
292    50
Name: sub, dtype: int32>

In [205]:
df['sub'].median()

8.0

In [207]:
df['sub'].var()

482.9166666666667

In [211]:
df['sub'].std()

21.975364995072702

In [213]:
df['sub'].min()

3

In [215]:
df['sub'].max()

50

In [219]:
df['sub'].quantile(0.25)

6.0

In [223]:
df['sub'].quantile(0.75)

19.25

In [225]:
df['sub'].mode()

0     3
1     7
2     9
3    50
Name: sub, dtype: int32